package com.lyc.crm.settings.mapper;

import com.lyc.crm.settings.domain.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Apr 25 22:36:31 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Apr 25 22:36:31 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Apr 25 22:36:31 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Apr 25 22:36:31 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Apr 25 22:36:31 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Apr 25 22:36:31 CST 2022
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据账号密码查询用户
     * @param map 储存账号密码的map
     * @return 返回用户对象
     */
    User selectUserByActAndPwd(Map<String,Object> map);

    /**
     * 查询所有用户
     * @return 返回包括所有用户的List
     */
    List<User> selectAllUser();

}